//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDuyurular
    {
        public byte id { get; set; }
        public string kategori { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
