//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKitap()
        {
            this.TblHareket = new HashSet<TblHareket>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public Nullable<int> kategori { get; set; }
        public Nullable<int> yazar { get; set; }
        public string basımyil { get; set; }
        public string yayinevi { get; set; }
        public string sayfa { get; set; }
        public Nullable<bool> durum { get; set; }
        public string kitapresim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHareket> TblHareket { get; set; }
        public virtual TblKategori TblKategori { get; set; }
        public virtual TblYazar TblYazar { get; set; }
    }
}
